### ISSUE TITLE
Patches fixing bugs available in Debian

### ISSUE THREAD

**Issue by charles2910** [alecthomas/devtodo#2]
Hi,

this application seens to not be maintained anymore (last commit 2009 and last release 2010), but people still use it.

So I've decided to remark if anyone decides to develop it again that there are a number of patches for devtodo available in
https://salsa.debian.org/debian/devtodo/-/tree/debian/master/debian/patches.

Cheers,
Charles

**Comment by alecthomas** [comment]
It is maintained, it's just stable. If there are patches, I'm unaware of them as nobody has submitted any. Also that link is empty.

**Comment by charles2910** [comment]
Hi,

> It is maintained, it's just stable.

that's really nice news. 

> I'm unaware of them as nobody has submitted any. Also that link is empty.

The package is orphaned in debian (i.e. there is no one taking care of it regularly) and I'm doing a QA work on it to keep it building by the new standards. So I was keeping it in a private space waiting until the package was accepted into the debian archive to push to debian repository on salsa.

The link should be working now.

**Comment by alecthomas** [comment]
Ah nice! Feel free to send through PRs if you'd like to upstream those patches.

**Comment by charles2910** [comment]
Ok, I'm going to finish the work on the build process and than take a closer look in the patches.
Thanks.

**Comment by charles2910** [comment]
Hi, Alec. I think it's safe to close this bug. 

I'd like to inform that I'm going to adopt this package on Debian so you may hear from me again.

Cheers,
Charles
