### ISSUE TITLE
License issue with libreadline

### ISSUE THREAD

**Issue by charles2910** [alecthomas/devtodo#4]
Hi, I've promised that I'd be back, so here I am XD.

Earlier this year I've received the following [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979101):

> This package depends on libreadline8 which is GPL-3+ licensed. According to debian/copyright parts of your package are GPL-2-only licensed. If that is also (transitively) the case for the binaries that link with libreadline.so.8 it might be legally problematic.
>
>There is an easy solution to the problem: Replacing the build dependency libreadline-dev with libreadline-gplv2-dev links with the GPL-2+ licensed older version. However, that is orphaned in Debian, so libeditreadline-dev should be preferred, which does not compile with your package without any patch. It links with the BSD-licensed libedit library which is a readline replacement.

And in [another mail](https://lists.debian.org/debian-legal/2021/01/msg00010.html), some suggestions are pointed:

> a) port the program to a GPLv2-compatible readline replacement (such as libedit or similar, possibly by using a shim library such as  libeditreadline)
>
> b) re-license the program from GPLv2-only to GPLv2-or-later
>
> c) disable any link with readline and make do without command editing/history (which is not great, but it could be necessary in  some cases)
>
> d) build the program by linking with an old GPLv2-compatible version of readline

I'd like to know if you would consider re-license the program as GPLv2-or-later or if you'd rather go with a different option.

Cheers,
Charles

**Comment by alecthomas** [comment]
I'd be happy with option b) but it's really not clear to me how to do that.

**Comment by charles2910** [comment]
Hi,

I'm gathering more info about this. The grand question is: do we need to gather the ok from every contributor or only yours?

After this, the ideal scenario would be to add the GPL boilerplate to the `*.c` and `*.h` files with the explicit 

> or  (at your option) any later version.

Or at least indicate in README the license of the software.

**Comment by charles2910** [comment]
Hi, sorry for taking so long to reply. Pandemic times have hit me hard.

So, to change the license to GPL-2+ we would need to have the ok from everyone who contributed to devtodo.

Also libreadline-gplv2-dev has been removed from debian, so option d) isn't possible anymore.

I've looked into the libedit compatibility layer to libreadline, but it doesn't cover all the functions used in `src/support.cc`, like `rl_delete_text` for example.

**Comment by alecthomas** [comment]
No problem, I understand.

> So, to change the license to GPL-2+ we would need to have the ok from everyone who contributed to devtodo.

Nobody but myself and you have contributed to DevTodo, so that's an easy one :)

**Comment by charles2910** [comment]
>  Nobody but myself and you have contributed to DevTodo, so that's an easy one :)

I thought that it would be a problem because I saw a bunch of names in the `AUTHORS` file. I guess then it would be fine to change the license.

**Comment by alecthomas** [comment]
Aah hmm, that is true... it's been so long that I don't remember, and only looked at the Git history. Those are definitely contributors, and there's no way I'm contacting them all.

**Comment by alecthomas** [comment]
Maybe it's time to just abandon packaging devtodo? devtodo2 exists and can load devtodo1 files, and has none of these issues, though it also has quite a bit less functionality, but maybe that's the path forward.

**Comment by charles2910** [comment]
> Maybe it's time to just abandon packaging devtodo?

Oh, come on, don't say that! Devtodo is a very nice working program. It has a ton of functionalities and it's very useful!

I'm working on a patch to use libedit. It's almost there, just having a little trouble with autocomplete.

**Comment by bgermann** [comment]
Fixed by afac3bf6670d25684a6a9aac6e05480d3aa67643

**Comment by charles2910** [comment]
Hi, @bgermann. I've only stated the following in #5, but I should have replied here too:

> You're welcome, but it's not that good yet, I'm finding some bugs in the compatibility layer :( and a few more changes will be needed

I'm trying to find some time to work on this again because one of the [bugs in the compatibility layer were solved recently](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=993153).

**Comment by charles2910** [comment]
Actually this was indeed fixed by afac3bf so we can close the bug in my opinion.
